services:
  - type: web
    name: doc-analyser
    env: python
    runtime: python311
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
